SET check_function_bodies = false;
INSERT INTO public.user_event (user_id, event_id) VALUES (1, 1);
INSERT INTO public.user_event (user_id, event_id) VALUES (2, 1);
INSERT INTO public.user_event (user_id, event_id) VALUES (3, 1);
INSERT INTO public.user_event (user_id, event_id) VALUES (1, 2);
INSERT INTO public.user_event (user_id, event_id) VALUES (2, 2);
INSERT INTO public.user_event (user_id, event_id) VALUES (3, 4);
INSERT INTO public.user_event (user_id, event_id) VALUES (2, 4);
INSERT INTO public.user_event (user_id, event_id) VALUES (1, 3);
INSERT INTO public.user_event (user_id, event_id) VALUES (3, 3);
