SET check_function_bodies = false;
INSERT INTO public.payment_detail (payment_id, detail_user_id) VALUES (1, 1);
INSERT INTO public.payment_detail (payment_id, detail_user_id) VALUES (1, 2);
INSERT INTO public.payment_detail (payment_id, detail_user_id) VALUES (1, 3);
INSERT INTO public.payment_detail (payment_id, detail_user_id) VALUES (2, 1);
INSERT INTO public.payment_detail (payment_id, detail_user_id) VALUES (2, 2);
INSERT INTO public.payment_detail (payment_id, detail_user_id) VALUES (3, 2);
INSERT INTO public.payment_detail (payment_id, detail_user_id) VALUES (3, 3);
INSERT INTO public.payment_detail (payment_id, detail_user_id) VALUES (4, 1);
INSERT INTO public.payment_detail (payment_id, detail_user_id) VALUES (4, 3);
